#NumPy

#Importing Numpy Module

In [0]:
import numpy as np

#Create a numpy array

In [0]:
X = np.array([1,2,3])

In [3]:
print(X)

[1 2 3]


#Type of numpy array

In [4]:
l = [2,3,4]

Y = np.asarray(l)
type(Y)

numpy.ndarray

#Creating a numpy array of float elements

In [0]:
Y = np.asarray(l, float)

In [6]:
print(Y)

[2. 3. 4.]


#Shape of numpy array

In [7]:
Y.shape

(3,)

#To know more about numpy array

In [0]:
np.array?

#creating np array of dimension (2,3)

In [0]:
X = np.array([[1,2,3],[4,5,6]])

In [10]:
X.shape

(2, 3)

In [11]:
print(X)

[[1 2 3]
 [4 5 6]]


#Accessing elements in np array

In [12]:
X[0,0]

1

In [13]:
X[1,0]

4

In [14]:
X[1,1:]

array([5, 6])

#Creating an array of (4,5) dimension with all zeroes

In [0]:
X = np.zeros((4,5))

In [16]:
print(X)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#Creating Identity Matrix

In [17]:
X = np.eye(4,4)
print(X)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#Creating a matrix with random values normalized between 0 & 1

In [0]:
X = np.random.random((4,5))

In [19]:
print(X)

[[0.48767321 0.69185107 0.73698116 0.21690773 0.259795  ]
 [0.40052935 0.45311929 0.12981354 0.11331242 0.02070426]
 [0.6300539  0.43030465 0.05530679 0.1232643  0.67460437]
 [0.63123316 0.0383946  0.78241453 0.55165161 0.54357856]]


#Transposing a Matrix

In [20]:
Z = X.T
print(Z)

[[0.48767321 0.40052935 0.6300539  0.63123316]
 [0.69185107 0.45311929 0.43030465 0.0383946 ]
 [0.73698116 0.12981354 0.05530679 0.78241453]
 [0.21690773 0.11331242 0.1232643  0.55165161]
 [0.259795   0.02070426 0.67460437 0.54357856]]


#Reshaping a Matrix

In [0]:
Y = X.reshape(1,20)

In [22]:
print(Y)

[[0.48767321 0.69185107 0.73698116 0.21690773 0.259795   0.40052935
  0.45311929 0.12981354 0.11331242 0.02070426 0.6300539  0.43030465
  0.05530679 0.1232643  0.67460437 0.63123316 0.0383946  0.78241453
  0.55165161 0.54357856]]


#Creating vectors of our own - similar to Range() function in python

In [23]:
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [0]:
B = np.arange(5)

since, A and B are vectors we can add, subtract and point wise multiply them.

In [25]:
C = A + B
D = A - B
E = A * B

print(C , D , E)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


#Broadcasting

In [26]:
F = A + 1
print(F)

[1 2 3 4 5]


#one way to get integer values while using random

In [27]:
x = np.floor(np.random.random((2,3))*10)
print(x)

[[1. 8. 1.]
 [6. 0. 3.]]


#Inner Product - similar to dot product of vectors

In [28]:
u = [2, 3, 4]
v = [-1, 0, 1]

w = np.inner(u, v)

print(w)

2


#Outer Product

In [29]:
w = np.outer(u, v)
print(w)

[[-2  0  2]
 [-3  0  3]
 [-4  0  4]]


#Dot Product

In [30]:
A = np.ones((2, 3))
B = np.ones((3, 2))

print(A , B)
np.dot(A, B)

[[1. 1. 1.]
 [1. 1. 1.]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 3.],
       [3., 3.]])

#Basic Operations

In [0]:
A = np.ones((2,3))

In [32]:
A.sum()

6.0

In [33]:
A.sum(axis = 0)

array([2., 2., 2.])

In [34]:
A.sum(axis = 1)

array([3., 3.])

In [35]:
A.max()

1.0